name: textlinting
on:
  push:
    branches:
      - vale-test

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Vale
      uses: errata-ai/vale-action@v1
      with:
        # path where vale checks just checking one file
        files: '["readme.md"]' 
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
